from __future__ import annotations

FORBIDDEN_CLAIMS = (
    "garanti",
    "guarantee",
    "sûr",
    "sure win",
    "safe bet",
    "certain",
    "100%",
    "blessure",
    "injury",
    "composition",
    "lineup",
    "mise",
    "pari recommandé",
    "gain",
    "ce pari va gagner",
    "pari sûr",
    "gain garanti",
    "expected goals",
    "possession",
    "tirs cadrés",
    "shots on target",
    "score final",
    "a gagné le match",
    "won the match",
    "final score",
)

UNSUPPORTED_INVENTED_TOPICS = (
    "xg",
    "xG",
    "expected goals",
    "possession",
    "tirs cadrés",
    "shots on target",
    "blessure",
    "injury",
    "composition",
    "lineup",
    "score final",
    "a gagné le match",
    "won the match",
    "final score",
)
